#!/bin/bash

# notSUDO Cron: "@reboot sleep 15; bash /caminho/FORA/do/drbd/Cluster"
# enabled systemd-networkd-wait-online.service

function init {
# ============================================================================ #

# Primary Node Private IP
IP1="170.10.1.2"
 # Secondary Node Private IP
IP2="170.10.1.3"

# ============================================================================ #

lognull="/dev/null"
logpath="/var/log/cluster"

while true; do
  data=$(date +"%Y_%m_%d_%H:%M")
  sleep 1;
  cluster00
done
}

function cluster00 {
  if ping -c 1 $IP1 &> $lognull && ping -c 1 $IP2 &> $lognull; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 01: Cluster not ping." >> $logpath
    sleep 1;
    cluster01
  fi
}

function cluster01 {
  for i in $(virsh list --all | grep "shut off" | awk '{print $2}'); do virsh start $i; echo "$data Started $i" >> $logpath; done
}

# Start #

init
