#!/bin/bash

# SUDO Cron: "@reboot sleep 15; bash /home/ubuntu/Script/Cluster"
# Use 'noauto' on FStab for /mnt/cluster
# ENABLEd systemd-networkd-wait-online.service

function init {
# ============================================================================ #

# Control Panel #

IP1="172.20.0.50" # Primary Node
IP2="172.20.0.51" # Secondary Node
IP3="172.20.0.1" # Local DHCP Server

mntpath1="/mnt/cluster01"
mntpath2="/mnt/cluster02"

lognull="/dev/null"
logpath="/var/log/cluster"

db="mysql"
webs="apache2"

# If Primary... Uncomment!
#clusterP0

# ============================================================================ #
while true; do
  data=$(date +"%Y_%m_%d_%H:%M")
  sleep 1;
  cluster00
done
}

# Function just for Primary!

# Var
control="0" # Default at boot

function clusterP0 {
  if [ $control = "1" ]; then # if 1:
    echo "Nothing more to do here." >> $lognull
  else # elif 0...
    control="1" # Only once in time, at boot!
    echo "First run." >> $logpath
    cluster03
    sleep 1;
  fi
}

# Functions to Both Servers!

# 00 - Local Ping
function cluster00 {
  if ping -c 1 $IP3 &> $lognull; then # Se pingou!
    echo "Nothing more to do here." >> $lognull
    sleep 1;
    cluster01
  else # Não pingou!
    echo "$data ERROR 01: Local ping. Canceling check." >> $logpath
  fi
}

# 01 - Cluster Ping
function cluster01 {
  if ping -c 1 $IP1 &> $lognull && ping -c 1 $IP2 &> $lognull; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 02: Cluster ping. Starting check." >> $logpath
    sleep 1;
    cluster02
  fi
}

# 02 - Mount Check
function cluster02 { # Se Montado!
  if grep -qs $mntpath1 /proc/mounts && grep -qs $mntpath2 /proc/mounts; then
    echo "Nothing more to do here." >> $lognull
  else # Não montado
    echo "$data ERROR 03: Paths not Mounted" >> $logpath
    sleep 1;
    cluster03
  fi
}

# 03 - Sequência de Estabilização
 
function cluster03 {
  if drbdadm primary --force all; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 04: DRBD" >> $lognull
  fi
  sleep 10;

  if mount $mntpath1; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 06: Cant Mount 01" >> $logpath
  fi
  sleep 1;
  
  if mount $mntpath2; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 07: Cant Mount 02" >> $logpath
  fi
  sleep 1;
  
  if systemctl restart smbd nmbd; then
    echo "Nothing more to do here." >> $lognull
  else 
    echo "$data ERROR 08: SMBd & NMBd" >> $logpath
  fi
  sleep 1;
  
  if systemctl start $db; then
    echo "Nothing more to do here." >> $lognull
  else 
    echo "$data ERROR 09: MySQL" >> $logpath
  fi
  sleep 10;
  
  if systemctl restart $webs; then
    echo "Nothing more to do here." >> $lognull
  else 
    echo "$data ERROR 10: Apache2" >> $logpath
  fi
  sleep 1;
}

# Start #

init
