#!/bin/bash

# SUDO Cron: "@reboot sleep 15; bash /home/ubuntu/Script/Cluster"
# Use 'noauto' on FStab for /mnt/cluster
# disable systemd-networkd-wait-online.service

function init {
# ============================================================================ #

# Control Panel #

IP1="172.20.0.50" # Primary Node
IP2="172.20.0.51" # Secondary Node
IP3="172.20.0.1" # Local DHCP Server

mntpath="/mnt/cluster01"

lognull="/dev/null"
logpath="/var/log/cluster"

# If Primary... Uncomment!
#clusterP0

# ============================================================================ #
while true; do
  data=$(date +"%Y_%m_%d_%H:%M")
  sleep 1;
  cluster00
done
}

# Function just for Primary!

# Var
control="0" # Default at boot

function clusterP0 {
  if [ $control = "1" ]; then # if 1:
    echo "Nothing more to do here." >> $lognull
  else # elif 0...
    control="1" # Only once in time, at boot!
    echo "First run." >> $logpath
    cluster03
    sleep 1;
  fi
}

# Functions to Both Servers!

# 00 - Local Ping
function cluster00 {
  if ping -c 1 $IP3 &> $lognull; then # Se pingou!
    echo "Nothing more to do here." >> $lognull
    sleep 1;
    cluster01
  else # Não pingou!
    echo "$data ERROR 01: Local ping. Canceling check." >> $logpath
  fi
}

# 01 - Cluster Ping
function cluster01 {
  if ping -c 1 $IP1 &> $lognull && ping -c 1 $IP2 &> $lognull; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 02: Cluster ping. Starting check." >> $logpath
    sleep 1;
    cluster02
  fi
}

# 02 - Mount Check
function cluster02 { # Se Montado!
  if grep -qs $mntpath /proc/mounts; then
    echo "Nothing more to do here." >> $lognull
  else # Não montado
    echo "$data ERROR 03: Path not Mounted" >> $logpath
    sleep 1;
    cluster03
  fi
}

# 03 - Sequência de Estabilização
 
function cluster03 {
  if drbdadm primary --force all; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 04: DRBD" >> $lognull
  fi
  sleep 10;

  if mount $mntpath1; then
    echo "Nothing more to do here." >> $lognull
  else
    echo "$data ERROR 06: Cant Mount 01" >> $logpath
  fi
  sleep 5;
  
  if systemctl restart smbd nmbd; then
    echo "Nothing more to do here." >> $lognull
  else 
    echo "$data ERROR 08: SMBd & NMBd" >> $logpath
  fi
  sleep 1;
  
  # Try Initialize all VMs
  for i in $(virsh list --name); do virsh start $i; done
}

# Start #

init
